name: Papyrus
description: "Your Pocket Library"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  #Design
  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0
  #State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  #Dependency Injection
  injectable: ^2.7.1+4
  get_it: ^9.2.0
  #Database (SQL)
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  #Util
  path: ^1.9.1
  path_provider: ^2.1.5
  file_picker: ^10.3.8
  uuid: ^4.5.2
  image: ^4.7.2
  #Readers
  pdfx: ^2.9.2
  epub_plus: ^5.1.0
  #Rendering
  flutter_widget_from_html: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.12.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

